#### MODULES ####

#module(load="imjournal") # provides support for systemd-journald logging
#module(load="imuxsock")  # provides support for local system logging (e.g. via logger command)
#module(load="imklog")    # provides kernel logging support (previously done by rklogd)
#module(load="immark")    # provides --MARK-- message capability

# Provides UDP syslog reception
# for parameters see http://www.rsyslog.com/doc/imudp.html

module(load="imudp") # needs to be done just once
input(type="imudp" port="514")

# Provides TCP syslog reception
# for parameters see http://www.rsyslog.com/doc/imtcp.html
module(load="imtcp") # needs to be done just once
input(type="imtcp" port="514")

#### GLOBAL DIRECTIVES ####

# Use default timestamp format
module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat"
       DirCreateMode="0755"
       FileCreateMode="0640"
       fileOwner="root"
       fileGroup="adm")

# An "In-Memory Queue" is created for remote logging.
global(workDirectory="/var/spool/rsyslog") # where to place spool files

# Set access rights for log files by default.
$umask 0022
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$PrivDropToGroup adm

$template dyn, "/opt/log/%HOSTNAME%/%PROGRAMNAME%.log"

*.warn ?dyn
& stop
